name: cp
favicon: null
layout_spectrum: 0.8936599164735526
typography_spectrum: 0.627304466208443
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5383624318055809
  lightness: 0.8141254291404039
  saturation: 0.6854005951900035
  rhythmicContrast: 0.8829729587305337
purpose: []
